//***************************ROMAN TO INTEGER***********************
class Solution {
public:
    int romanToInt(string s) {

        int n=s.length();

        unordered_map<char, int> roman = {
            {'I', 1},
            {'V', 5},
            {'X', 10},
            {'L', 50},
            {'C', 100},
            {'D', 500},
            {'M', 1000}
        };

        int total=0;

        for(int i=0;i<n;i++){
             if(roman[s[i]]<roman[s[i+1]] && i<n-1){
                total-=roman[s[i]];
             }
             else{
                total+=roman[s[i]];
             }
        }
        return total;
        
    }
};
